#!/usr/bin/env python3

def main():
    import argparse
    import json
    from ruamel.yaml import YAML
    yaml = YAML(typ='safe')

    parser = argparse.ArgumentParser()
    parser.add_argument('INPUT', help='yaml file')
    parser.add_argument('-o', '--output', required=True, help='output json file')
    args = parser.parse_args()

    with open(args.INPUT) as f:
        y = yaml.load(f)

    # take advantage of python 3.7's insertion-order dicts to put this comment at the top
    out = {'COMMENT': 'This file is autogenerated.  Please do not edit it directly.  See the convert-yaml.py script.'}
    out.update(transform_binhack_yaml(y))

    with open(args.output, 'w') as f:
        json.dump(out, f, indent=4)

def transform_binhack_yaml(val):
    if isinstance(val, list):
        return ' // '.join(x.strip() for x in val)
    if isinstance(val, dict):
        return { k:transform_binhack_yaml(v) for (k, v) in val.items() }
    return val

if __name__ == '__main__':
    main()
